version: '3'
services:
  openbmclapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${UID-1000}
    env_file:
      - .env
    volumes:
      - ./opt/mcim:/opt/mcim/cache
    network_mode: host
    user: "${UID-1000}:${GID-1000}"
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
